/**
 * Entity seed.
 *
 * Consulting firms are ordinary entities with `kind: 'consulting_firm'`. They get no
 * special table, no special ranking and no reserved place in the navigation — the
 * only thing that distinguishes them is a value in an enum, which is exactly the point
 * of the "Accenture is not the product foundation" requirement.
 *
 * `requiresContext` on an alias means the alias is an ordinary word or too short to
 * match safely on its own ("Next", "Meta", "EY", "H&M"). Those need a corroborating
 * signal before entity resolution accepts them.
 */

export interface EntitySeed {
  slug: string;
  kind: 'company' | 'consulting_firm' | 'person' | 'technology' | 'institution';
  name: string;
  legalName?: string;
  description: string;
  officialDomain: string;
  ticker?: string;
  /**
   * The company's number in its national business register.
   *
   * Only for companies whose accounts are reachable only that way — a private European
   * company files nothing on a regulated market, so neither EDGAR nor ESEF holds it.
   * Verified by hand against the register before it goes in: a wrong number here is
   * another company's revenue under this one's name, which is the failure the whole
   * matching apparatus exists to prevent.
   */
  registrationNumber?: string;
  hq?: string;
  primaryIndustrySlug?: string;
  industrySlugs?: string[];
  /** Fictional entity used only by demo fixtures. Badged everywhere it appears. */
  isDemo?: boolean;
  businessModelSlug?: string;
  aliases: { alias: string; type?: string; requiresContext?: boolean; language?: string }[];
}

export const ENTITIES: EntitySeed[] = [
  // ── Retail, fashion and consumer ──────────────────────────────────────────
  {
    slug: 'hm-group',
    kind: 'company',
    name: 'H&M Group',
    legalName: 'H & M Hennes & Mauritz AB',
    description:
      'Swedish multinational clothing retailer operating a vertically integrated fast-fashion model across multiple brands.',
    officialDomain: 'hmgroup.com',
    ticker: 'HM-B',
    hq: 'sweden',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'retail'],
    businessModelSlug: 'fast-fashion',
    aliases: [
      { alias: 'H&M Group' },
      { alias: 'H & M Hennes & Mauritz', type: 'legal' },
      { alias: 'Hennes & Mauritz', type: 'legal' },
      { alias: 'H&M', requiresContext: true },
      { alias: 'HM-B', type: 'ticker', requiresContext: true },
    ],
  },
  {
    slug: 'inditex',
    kind: 'company',
    name: 'Inditex',
    legalName: 'Industria de Diseño Textil, S.A.',
    description:
      'Spanish fashion group and owner of Zara, operating a short-lead-time vertically integrated model.',
    officialDomain: 'inditex.com',
    ticker: 'ITX',
    hq: 'spain',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'retail'],
    businessModelSlug: 'fast-fashion',
    aliases: [
      { alias: 'Inditex' },
      { alias: 'Industria de Diseño Textil', type: 'legal', language: 'es' },
      { alias: 'Zara', type: 'trade' },
      { alias: 'ITX', type: 'ticker', requiresContext: true },
    ],
  },
  {
    slug: 'zalando',
    kind: 'company',
    name: 'Zalando',
    legalName: 'Zalando SE',
    description: 'European online fashion platform combining retail and a partner marketplace.',
    officialDomain: 'zalando.com',
    ticker: 'ZAL',
    hq: 'germany',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'retail'],
    businessModelSlug: 'marketplace',
    aliases: [
      { alias: 'Zalando' },
      { alias: 'Zalando SE', type: 'legal' },
      { alias: 'ZAL', type: 'ticker', requiresContext: true },
    ],
  },
  {
    slug: 'c-and-a',
    kind: 'company',
    name: 'C&A',
    legalName: 'C&A Mode GmbH & Co. KG',
    description: 'European clothing retail chain operating across continental Europe.',
    officialDomain: 'c-and-a.com',
    hq: 'germany',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'retail'],
    aliases: [
      { alias: 'C&A', requiresContext: true },
      { alias: 'C and A', requiresContext: true },
      { alias: 'C&A Mode', type: 'legal' },
    ],
  },
  {
    slug: 'nike',
    kind: 'company',
    name: 'Nike',
    legalName: 'NIKE, Inc.',
    description:
      'American athletic footwear and apparel brand with a direct-to-consumer led distribution strategy.',
    officialDomain: 'nike.com',
    ticker: 'NKE',
    hq: 'united-states',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'consumer-goods'],
    businessModelSlug: 'premium-brand',
    aliases: [
      { alias: 'Nike', requiresContext: true },
      { alias: 'NIKE Inc', type: 'legal' },
      { alias: 'NKE', type: 'ticker', requiresContext: true },
    ],
  },
  {
    slug: 'adidas',
    kind: 'company',
    name: 'adidas',
    legalName: 'adidas AG',
    description: 'German sportswear manufacturer and brand.',
    officialDomain: 'adidas-group.com',
    ticker: 'ADS',
    hq: 'germany',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'consumer-goods'],
    businessModelSlug: 'premium-brand',
    aliases: [
      { alias: 'adidas' },
      { alias: 'adidas AG', type: 'legal' },
      { alias: 'ADS', type: 'ticker', requiresContext: true },
    ],
  },
  {
    slug: 'uniqlo',
    kind: 'company',
    name: 'Uniqlo',
    legalName: 'Fast Retailing Co., Ltd.',
    description:
      'Japanese apparel retailer, principal brand of Fast Retailing, built on a core-range LifeWear model.',
    officialDomain: 'fastretailing.com',
    ticker: '9983',
    hq: 'japan',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'retail'],
    businessModelSlug: 'vertical-retail',
    aliases: [{ alias: 'Uniqlo' }, { alias: 'Fast Retailing', type: 'legal' }, { alias: 'UNIQLO' }],
  },
  {
    slug: 'shein',
    kind: 'company',
    name: 'Shein',
    description:
      'Digital-first apparel company operating an on-demand micro-batch production model.',
    officialDomain: 'shein.com',
    hq: 'china',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'retail'],
    businessModelSlug: 'ultra-fast-digital',
    aliases: [
      { alias: 'Shein', requiresContext: true },
      { alias: 'SHEIN', requiresContext: true },
    ],
  },
  {
    slug: 'walmart',
    kind: 'company',
    name: 'Walmart',
    legalName: 'Walmart Inc.',
    description:
      'American multinational retail corporation operating hypermarkets, discount stores and a growing marketplace and retail media business.',
    officialDomain: 'corporate.walmart.com',
    ticker: 'WMT',
    hq: 'united-states',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'Walmart' },
      { alias: 'Walmart Inc', type: 'legal' },
      { alias: 'WMT', type: 'ticker', requiresContext: true },
      { alias: 'Walmart Connect', type: 'trade' },
    ],
  },
  {
    slug: 'amazon',
    kind: 'company',
    name: 'Amazon',
    legalName: 'Amazon.com, Inc.',
    description:
      'American technology and retail company operating a marketplace, cloud infrastructure (AWS), advertising and logistics network.',
    officialDomain: 'aboutamazon.com',
    ticker: 'AMZN',
    hq: 'united-states',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'technology-ai'],
    businessModelSlug: 'marketplace',
    aliases: [
      { alias: 'Amazon', requiresContext: true },
      { alias: 'Amazon.com', type: 'legal' },
      { alias: 'AWS', type: 'abbreviation' },
      { alias: 'Amazon Web Services', type: 'trade' },
      { alias: 'AMZN', type: 'ticker', requiresContext: true },
    ],
  },

  // ── Technology ────────────────────────────────────────────────────────────
  {
    slug: 'openai',
    kind: 'company',
    name: 'OpenAI',
    legalName: 'OpenAI, Inc.',
    description:
      'AI research and deployment company developing the GPT family of foundation models.',
    officialDomain: 'openai.com',
    hq: 'united-states',
    primaryIndustrySlug: 'technology-ai',
    industrySlugs: ['technology-ai'],
    businessModelSlug: 'model-provider',
    aliases: [{ alias: 'OpenAI' }, { alias: 'Open AI' }, { alias: 'ChatGPT', type: 'trade' }],
  },
  {
    slug: 'anthropic',
    kind: 'company',
    name: 'Anthropic',
    legalName: 'Anthropic PBC',
    description:
      'AI safety and research company developing the Claude family of foundation models.',
    officialDomain: 'anthropic.com',
    hq: 'united-states',
    primaryIndustrySlug: 'technology-ai',
    industrySlugs: ['technology-ai'],
    businessModelSlug: 'model-provider',
    aliases: [{ alias: 'Anthropic' }, { alias: 'Claude', type: 'trade', requiresContext: true }],
  },
  {
    slug: 'nvidia',
    kind: 'company',
    name: 'NVIDIA',
    legalName: 'NVIDIA Corporation',
    description:
      'Designer of GPUs and accelerated computing platforms underpinning most AI training and inference.',
    officialDomain: 'nvidia.com',
    ticker: 'NVDA',
    hq: 'united-states',
    primaryIndustrySlug: 'technology-ai',
    industrySlugs: ['technology-ai'],
    businessModelSlug: 'accelerated-compute',
    aliases: [
      { alias: 'NVIDIA' },
      { alias: 'Nvidia' },
      { alias: 'NVDA', type: 'ticker', requiresContext: true },
    ],
  },
  {
    slug: 'microsoft',
    kind: 'company',
    name: 'Microsoft',
    legalName: 'Microsoft Corporation',
    description:
      'Software and cloud company operating Azure, Microsoft 365 and a portfolio of AI products.',
    officialDomain: 'microsoft.com',
    ticker: 'MSFT',
    hq: 'united-states',
    primaryIndustrySlug: 'technology-ai',
    industrySlugs: ['technology-ai'],
    businessModelSlug: 'hyperscaler',
    aliases: [
      { alias: 'Microsoft' },
      { alias: 'Azure', type: 'trade' },
      { alias: 'MSFT', type: 'ticker', requiresContext: true },
      { alias: 'Microsoft Copilot', type: 'trade' },
    ],
  },
  {
    slug: 'google',
    kind: 'company',
    name: 'Google',
    legalName: 'Alphabet Inc.',
    description:
      'Technology company operating search, advertising, Google Cloud and the Gemini model family.',
    officialDomain: 'blog.google',
    ticker: 'GOOGL',
    hq: 'united-states',
    primaryIndustrySlug: 'technology-ai',
    industrySlugs: ['technology-ai'],
    businessModelSlug: 'hyperscaler',
    aliases: [
      { alias: 'Google' },
      { alias: 'Alphabet', type: 'legal', requiresContext: true },
      { alias: 'Google Cloud', type: 'trade' },
      { alias: 'Gemini', type: 'trade', requiresContext: true },
      { alias: 'DeepMind', type: 'trade' },
    ],
  },
  {
    slug: 'meta',
    kind: 'company',
    name: 'Meta',
    legalName: 'Meta Platforms, Inc.',
    description:
      'Technology company operating social platforms and developing the Llama open-weight model family.',
    officialDomain: 'about.fb.com',
    ticker: 'META',
    hq: 'united-states',
    primaryIndustrySlug: 'technology-ai',
    industrySlugs: ['technology-ai'],
    aliases: [
      { alias: 'Meta', requiresContext: true },
      { alias: 'Meta Platforms', type: 'legal' },
      { alias: 'Facebook', type: 'former' },
      { alias: 'Llama', type: 'trade', requiresContext: true },
    ],
  },
  {
    slug: 'palantir',
    kind: 'company',
    name: 'Palantir',
    legalName: 'Palantir Technologies Inc.',
    description:
      'Enterprise data and decision platform vendor working with commercial and government customers.',
    officialDomain: 'palantir.com',
    ticker: 'PLTR',
    hq: 'united-states',
    primaryIndustrySlug: 'technology-ai',
    industrySlugs: ['technology-ai'],
    businessModelSlug: 'enterprise-saas',
    aliases: [
      { alias: 'Palantir' },
      { alias: 'Palantir Technologies', type: 'legal' },
      { alias: 'Foundry', type: 'trade', requiresContext: true },
      { alias: 'PLTR', type: 'ticker', requiresContext: true },
    ],
  },

  // ── Consulting and professional services ──────────────────────────────────
  // Ordinary entities. Monitored, ranked and filtered by the same mechanisms as
  // every other company.
  {
    slug: 'accenture',
    kind: 'consulting_firm',
    name: 'Accenture',
    legalName: 'Accenture plc',
    description:
      'Global professional services company providing strategy, consulting, technology and operations services.',
    officialDomain: 'accenture.com',
    ticker: 'ACN',
    hq: 'global',
    industrySlugs: ['technology-ai'],
    aliases: [
      { alias: 'Accenture' },
      { alias: 'Accenture plc', type: 'legal' },
      { alias: 'ACN', type: 'ticker', requiresContext: true },
      { alias: 'Accenture Song', type: 'trade' },
    ],
  },
  {
    slug: 'mckinsey',
    kind: 'consulting_firm',
    name: 'McKinsey & Company',
    description: 'Global management consulting firm.',
    officialDomain: 'mckinsey.com',
    hq: 'global',
    aliases: [
      { alias: 'McKinsey' },
      { alias: 'McKinsey & Company', type: 'legal' },
      { alias: 'QuantumBlack', type: 'trade' },
    ],
  },
  {
    slug: 'bcg',
    kind: 'consulting_firm',
    name: 'Boston Consulting Group',
    description: 'Global management consulting firm.',
    officialDomain: 'bcg.com',
    hq: 'global',
    aliases: [
      { alias: 'BCG' },
      { alias: 'Boston Consulting Group', type: 'legal' },
      { alias: 'BCG X', type: 'trade' },
    ],
  },
  {
    slug: 'bain',
    kind: 'consulting_firm',
    name: 'Bain & Company',
    description: 'Global management consulting firm.',
    officialDomain: 'bain.com',
    hq: 'global',
    aliases: [{ alias: 'Bain & Company' }, { alias: 'Bain', requiresContext: true }],
  },
  {
    slug: 'deloitte',
    kind: 'consulting_firm',
    name: 'Deloitte',
    description: 'Global professional services network.',
    officialDomain: 'deloitte.com',
    hq: 'global',
    aliases: [{ alias: 'Deloitte' }, { alias: 'Deloitte Touche Tohmatsu', type: 'legal' }],
  },
  {
    slug: 'pwc',
    kind: 'consulting_firm',
    name: 'PwC',
    description: 'Global professional services network.',
    officialDomain: 'pwc.com',
    hq: 'global',
    aliases: [
      { alias: 'PwC', requiresContext: true },
      { alias: 'PricewaterhouseCoopers', type: 'legal' },
    ],
  },
  {
    slug: 'ey',
    kind: 'consulting_firm',
    name: 'EY',
    description: 'Global professional services network.',
    officialDomain: 'ey.com',
    hq: 'global',
    aliases: [
      { alias: 'EY', requiresContext: true },
      { alias: 'Ernst & Young', type: 'legal' },
    ],
  },
  {
    slug: 'kpmg',
    kind: 'consulting_firm',
    name: 'KPMG',
    description: 'Global professional services network.',
    officialDomain: 'kpmg.com',
    hq: 'global',
    aliases: [{ alias: 'KPMG' }],
  },
  {
    slug: 'capgemini',
    kind: 'consulting_firm',
    name: 'Capgemini',
    description: 'Global technology and consulting services company.',
    officialDomain: 'capgemini.com',
    hq: 'global',
    aliases: [{ alias: 'Capgemini' }, { alias: 'Capgemini Invent', type: 'trade' }],
  },
  {
    slug: 'ibm-consulting',
    kind: 'consulting_firm',
    name: 'IBM Consulting',
    description: 'Consulting arm of IBM.',
    officialDomain: 'ibm.com',
    hq: 'global',
    aliases: [{ alias: 'IBM Consulting' }, { alias: 'IBM', requiresContext: true }],
  },
  {
    slug: 'tcs',
    kind: 'consulting_firm',
    name: 'Tata Consultancy Services',
    description: 'Indian multinational IT services and consulting company.',
    officialDomain: 'tcs.com',
    hq: 'global',
    aliases: [
      { alias: 'TCS', requiresContext: true },
      { alias: 'Tata Consultancy Services', type: 'legal' },
    ],
  },
  {
    slug: 'infosys',
    kind: 'consulting_firm',
    name: 'Infosys',
    description: 'Indian multinational IT services and consulting company.',
    officialDomain: 'infosys.com',
    hq: 'global',
    aliases: [{ alias: 'Infosys' }],
  },
  {
    slug: 'cognizant',
    kind: 'consulting_firm',
    name: 'Cognizant',
    description: 'American multinational IT services and consulting company.',
    officialDomain: 'cognizant.com',
    hq: 'global',
    aliases: [{ alias: 'Cognizant' }],
  },

  // ── Demo entities ─────────────────────────────────────────────────────────
  // Fictional companies used by the demo fixtures. They exist so the fixtures can
  // exercise entity resolution, cross-source clustering and contradiction detection.
  // Marked `isDemo`, and every derived item is badged accordingly in the UI.
  {
    slug: 'northwind-apparel',
    kind: 'company',
    name: 'Northwind Apparel',
    isDemo: true,
    description: 'Fictional fashion retailer used in demo fixtures. Not a real company.',
    officialDomain: 'demo.local',
    hq: 'europe',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'retail'],
    aliases: [{ alias: 'Northwind Apparel' }, { alias: 'Northwind', requiresContext: true }],
  },
  {
    slug: 'meridian-retail-group',
    kind: 'company',
    name: 'Meridian Retail Group',
    isDemo: true,
    description:
      'Fictional grocery and general merchandise retailer used in demo fixtures. Not a real company.',
    officialDomain: 'demo.local',
    hq: 'europe',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail'],
    aliases: [{ alias: 'Meridian Retail Group' }, { alias: 'Meridian', requiresContext: true }],
  },
  {
    slug: 'halden-ai',
    kind: 'company',
    name: 'Halden AI',
    isDemo: true,
    description: 'Fictional demand forecasting vendor used in demo fixtures. Not a real company.',
    officialDomain: 'demo.local',
    hq: 'europe',
    primaryIndustrySlug: 'technology-ai',
    industrySlugs: ['technology-ai'],
    aliases: [{ alias: 'Halden AI' }, { alias: 'Halden', requiresContext: true }],
  },
  {
    slug: 'calder-stores',
    kind: 'company',
    name: 'Calder Stores',
    isDemo: true,
    description: 'Fictional retail chain used in demo fixtures. Not a real company.',
    officialDomain: 'demo.local',
    hq: 'europe',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail'],
    aliases: [{ alias: 'Calder Stores' }, { alias: 'Calder', requiresContext: true }],
  },

  // ── Institutions ──────────────────────────────────────────────────────────
  {
    slug: 'european-commission',
    kind: 'institution',
    name: 'European Commission',
    description:
      'Executive branch of the European Union; originator of most EU regulation affecting these industries.',
    officialDomain: 'ec.europa.eu',
    hq: 'europe',
    aliases: [{ alias: 'European Commission' }, { alias: 'EU Commission' }],
  },
  {
    slug: 'nist',
    kind: 'institution',
    name: 'NIST',
    legalName: 'National Institute of Standards and Technology',
    description: 'US standards body; publisher of the AI Risk Management Framework.',
    officialDomain: 'nist.gov',
    hq: 'united-states',
    aliases: [
      { alias: 'NIST' },
      { alias: 'National Institute of Standards and Technology', type: 'legal' },
    ],
  },

  /*
   * Major companies across consumer goods, retail and travel.
   *
   * Reference data, not intelligence. Each row is a public company with its public
   * name, domain, ticker and industry — the sort of thing any market-monitoring tool
   * needs in order to recognise what it is being asked about. Nothing here records a
   * relationship, an assessment or a maturity judgement about any of them, and nothing
   * marks any row as anyone's client. That would be client analysis rather than a
   * company list, and it has no business in a repository that gets shared.
   *
   * Most have no source registered, so they will show no coverage. That is the honest
   * state and the product says so, naming the source that would change it. Being able to
   * ask about a company and be told "we are not monitoring them" is the point; returning
   * nothing at all was the bug.
   */

  // ── Tobacco & nicotine ────────────────────────────────────────────────────
  {
    slug: 'philip-morris-international',
    kind: 'company',
    name: 'Philip Morris International',
    legalName: 'Philip Morris International Inc.',
    description:
      'Tobacco and nicotine company, transitioning from combustible cigarettes towards heated-tobacco and vapour products.',
    officialDomain: 'pmi.com',
    ticker: 'PM',
    hq: 'switzerland',
    primaryIndustrySlug: 'tobacco',
    industrySlugs: ['tobacco', 'consumer-goods'],
    aliases: [
      { alias: 'Philip Morris International' },
      { alias: 'Philip Morris' },
      { alias: 'PMI', type: 'abbreviation', requiresContext: true },
      { alias: 'Philip Morris International Inc.', type: 'legal' },
      { alias: 'IQOS', type: 'brand' },
      { alias: 'PM', type: 'ticker', requiresContext: true },
    ],
  },
  {
    slug: 'japan-tobacco-international',
    kind: 'company',
    name: 'Japan Tobacco International',
    legalName: 'JT International SA',
    description: 'International tobacco business of Japan Tobacco, operating outside Japan.',
    officialDomain: 'jti.com',
    hq: 'switzerland',
    primaryIndustrySlug: 'tobacco',
    industrySlugs: ['tobacco', 'consumer-goods'],
    aliases: [
      { alias: 'Japan Tobacco International' },
      { alias: 'JTI', type: 'abbreviation' },
      { alias: 'Japan Tobacco' },
      { alias: 'JT International', type: 'legal' },
    ],
  },
  {
    slug: 'british-american-tobacco',
    kind: 'company',
    name: 'British American Tobacco',
    legalName: 'British American Tobacco p.l.c.',
    description:
      'Multinational tobacco and nicotine company with a portfolio spanning combustibles, vapour and modern oral products.',
    officialDomain: 'bat.com',
    ticker: 'BATS',
    hq: 'united-kingdom',
    primaryIndustrySlug: 'tobacco',
    industrySlugs: ['tobacco', 'consumer-goods'],
    aliases: [
      { alias: 'British American Tobacco' },
      { alias: 'BAT', type: 'abbreviation', requiresContext: true },
      { alias: 'Vuse', type: 'brand' },
      { alias: 'Glo', type: 'brand', requiresContext: true },
    ],
  },
  {
    slug: 'imperial-brands',
    kind: 'company',
    name: 'Imperial Brands',
    description: 'Tobacco and nicotine company with cigarette, vapour and oral nicotine brands.',
    officialDomain: 'imperialbrandsplc.com',
    ticker: 'IMB',
    hq: 'united-kingdom',
    primaryIndustrySlug: 'tobacco',
    industrySlugs: ['tobacco', 'consumer-goods'],
    aliases: [{ alias: 'Imperial Brands' }, { alias: 'Imperial Tobacco' }],
  },
  {
    slug: 'altria',
    kind: 'company',
    name: 'Altria Group',
    description: 'United States tobacco and nicotine group.',
    officialDomain: 'altria.com',
    ticker: 'MO',
    hq: 'united-states',
    primaryIndustrySlug: 'tobacco',
    industrySlugs: ['tobacco', 'consumer-goods'],
    aliases: [{ alias: 'Altria' }, { alias: 'Altria Group' }],
  },

  // ── Grocery, discount and specialist retail ───────────────────────────────
  {
    slug: 'migros',
    kind: 'company',
    name: 'Migros',
    description:
      'Swiss retail group and cooperative, the country’s largest grocer, with own-brand manufacturing and adjacent retail formats.',
    officialDomain: 'migros.ch',
    hq: 'switzerland',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    aliases: [{ alias: 'Migros' }, { alias: 'Migros-Genossenschafts-Bund', type: 'legal' }],
  },
  {
    slug: 'coop-switzerland',
    kind: 'company',
    name: 'Coop (Switzerland)',
    description:
      'Swiss retail and wholesale cooperative operating grocery, convenience and specialist formats.',
    officialDomain: 'coop.ch',
    hq: 'switzerland',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    aliases: [{ alias: 'Coop Schweiz' }, { alias: 'Coop Genossenschaft', type: 'legal' }],
  },
  {
    slug: 'aldi-sued',
    kind: 'company',
    name: 'Aldi Süd',
    description:
      'German discount grocery group operating in southern Germany and internationally, including as Aldi in several markets.',
    officialDomain: 'aldi-sued.de',
    hq: 'germany',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail'],
    aliases: [{ alias: 'Aldi Süd' }, { alias: 'Aldi Sud' }, { alias: 'Aldi South' }],
  },
  {
    slug: 'aldi-nord',
    kind: 'company',
    name: 'Aldi Nord',
    description:
      'German discount grocery group operating in northern Germany and across Europe, including the Trader Joe’s business in the United States.',
    officialDomain: 'aldi-nord.de',
    hq: 'germany',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail'],
    aliases: [
      { alias: 'Aldi Nord' },
      { alias: 'Aldi North' },
      { alias: 'Trader Joe’s', type: 'brand' },
    ],
  },
  {
    slug: 'schwarz-gruppe',
    kind: 'company',
    name: 'Schwarz Gruppe',
    description:
      'German retail group behind Lidl and Kaufland, with recycling and IT services businesses alongside the stores.',
    officialDomain: 'gruppe.schwarz',
    hq: 'germany',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail'],
    aliases: [
      { alias: 'Schwarz Gruppe' },
      { alias: 'Schwarz Group' },
      { alias: 'Lidl', type: 'brand' },
      { alias: 'Kaufland', type: 'brand' },
      { alias: 'Schwarz Digits', type: 'brand' },
    ],
  },
  {
    slug: 'rewe-group',
    kind: 'company',
    name: 'REWE Group',
    description:
      'German retail and tourism cooperative operating supermarkets, discount and travel businesses.',
    officialDomain: 'rewe-group.com',
    hq: 'germany',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'travel'],
    aliases: [
      { alias: 'REWE Group' },
      { alias: 'Rewe' },
      { alias: 'Penny', type: 'brand', requiresContext: true },
      { alias: 'DER Touristik', type: 'brand' },
    ],
  },
  {
    slug: 'mediamarktsaturn',
    kind: 'company',
    name: 'MediaMarktSaturn',
    description:
      'European consumer electronics retail group operating the MediaMarkt and Saturn formats.',
    officialDomain: 'mediamarktsaturn.com',
    hq: 'germany',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail'],
    aliases: [
      { alias: 'MediaMarktSaturn' },
      { alias: 'Media Markt' },
      { alias: 'MediaMarkt' },
      { alias: 'Saturn', type: 'brand', requiresContext: true },
      { alias: 'Ceconomy' },
    ],
  },
  {
    slug: 'mcdonalds',
    kind: 'company',
    name: "McDonald's",
    description: 'Global quick-service restaurant franchisor and operator.',
    officialDomain: 'mcdonalds.com',
    ticker: 'MCD',
    hq: 'united-states',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    aliases: [
      { alias: "McDonald's" },
      { alias: 'McDonalds' },
      { alias: 'MCD', type: 'ticker', requiresContext: true },
    ],
  },

  // ── Sportswear and apparel ────────────────────────────────────────────────
  {
    slug: 'adidas',
    kind: 'company',
    name: 'adidas',
    legalName: 'adidas AG',
    description:
      'German sportswear and footwear group selling through wholesale, owned retail and direct digital channels.',
    officialDomain: 'adidas-group.com',
    ticker: 'ADS',
    hq: 'germany',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'consumer-goods', 'retail'],
    aliases: [
      { alias: 'adidas' },
      { alias: 'adidas AG', type: 'legal' },
      { alias: 'ADS', type: 'ticker', requiresContext: true },
    ],
  },
  {
    slug: 'on-running',
    kind: 'company',
    name: 'On',
    legalName: 'On Holding AG',
    description: 'Swiss performance running and sportswear brand, direct-to-consumer led.',
    officialDomain: 'on-running.com',
    ticker: 'ONON',
    hq: 'switzerland',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'consumer-goods'],
    aliases: [
      { alias: 'On Running' },
      { alias: 'On Holding', type: 'legal' },
      { alias: 'ONON', type: 'ticker', requiresContext: true },
    ],
  },
  {
    slug: 'triumph',
    kind: 'company',
    name: 'Triumph International',
    description: 'Swiss-headquartered lingerie and intimate apparel group.',
    officialDomain: 'triumph.com',
    hq: 'switzerland',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'consumer-goods'],
    aliases: [{ alias: 'Triumph International' }, { alias: 'Triumph', requiresContext: true }],
  },

  // ── Food, beverage and packaged goods ─────────────────────────────────────
  {
    slug: 'nestle',
    kind: 'company',
    name: 'Nestlé',
    description: 'Swiss food and beverage group, the largest by revenue worldwide.',
    officialDomain: 'nestle.com',
    ticker: 'NESN',
    hq: 'switzerland',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [{ alias: 'Nestlé' }, { alias: 'Nestle' }, { alias: 'Nestlé S.A.', type: 'legal' }],
  },
  {
    slug: 'unilever',
    kind: 'company',
    name: 'Unilever',
    description:
      'Consumer goods group spanning beauty, personal care, home care, nutrition and ice cream.',
    officialDomain: 'unilever.com',
    ticker: 'ULVR',
    hq: 'united-kingdom',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods'],
    aliases: [{ alias: 'Unilever' }, { alias: 'Unilever PLC', type: 'legal' }],
  },
  {
    slug: 'procter-and-gamble',
    kind: 'company',
    name: 'Procter & Gamble',
    description:
      'United States consumer goods group across fabric, home, baby, beauty and grooming categories.',
    officialDomain: 'pg.com',
    ticker: 'PG',
    hq: 'united-states',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods'],
    aliases: [
      { alias: 'Procter & Gamble' },
      { alias: 'P&G', type: 'abbreviation' },
      { alias: 'Procter and Gamble' },
    ],
  },
  {
    slug: 'pepsico',
    kind: 'company',
    name: 'PepsiCo',
    description: 'Beverages and convenient foods group.',
    officialDomain: 'pepsico.com',
    ticker: 'PEP',
    hq: 'united-states',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [
      { alias: 'PepsiCo' },
      { alias: 'Pepsi', type: 'brand' },
      { alias: 'Frito-Lay', type: 'brand' },
    ],
  },
  {
    slug: 'coca-cola-company',
    kind: 'company',
    name: 'The Coca-Cola Company',
    description:
      'Beverage concentrate and brand owner operating through a franchised bottling system.',
    officialDomain: 'coca-colacompany.com',
    ticker: 'KO',
    hq: 'united-states',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [
      { alias: 'The Coca-Cola Company' },
      { alias: 'Coca-Cola' },
      { alias: 'Coke', requiresContext: true },
    ],
  },
  {
    slug: 'coca-cola-hbc',
    kind: 'company',
    name: 'Coca-Cola HBC',
    description: 'Bottler of Coca-Cola brands across Europe, Africa and adjacent markets.',
    officialDomain: 'coca-colahellenic.com',
    ticker: 'CCH',
    hq: 'switzerland',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [
      { alias: 'Coca-Cola HBC' },
      { alias: 'Coca-Cola Hellenic' },
      { alias: 'CCH', type: 'ticker', requiresContext: true },
    ],
  },
  {
    slug: 'danone',
    kind: 'company',
    name: 'Danone',
    description: 'Food group focused on dairy, plant-based, waters and specialised nutrition.',
    officialDomain: 'danone.com',
    ticker: 'BN',
    hq: 'france',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [{ alias: 'Danone' }, { alias: 'Groupe Danone', type: 'legal' }],
  },
  {
    slug: 'mondelez',
    kind: 'company',
    name: 'Mondelēz International',
    description: 'Snacking group across chocolate, biscuits and confectionery.',
    officialDomain: 'mondelezinternational.com',
    ticker: 'MDLZ',
    hq: 'united-states',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [
      { alias: 'Mondelēz International' },
      { alias: 'Mondelez' },
      { alias: 'MDLZ', type: 'ticker', requiresContext: true },
    ],
  },
  {
    slug: 'kraft-heinz',
    kind: 'company',
    name: 'The Kraft Heinz Company',
    description: 'Packaged food group across condiments, cheese, meals and snacks.',
    officialDomain: 'kraftheinzcompany.com',
    ticker: 'KHC',
    hq: 'united-states',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [{ alias: 'Kraft Heinz' }, { alias: 'The Kraft Heinz Company', type: 'legal' }],
  },
  {
    slug: 'general-mills',
    kind: 'company',
    name: 'General Mills',
    description: 'Packaged food group across cereal, snacks, meals and pet food.',
    officialDomain: 'generalmills.com',
    ticker: 'GIS',
    hq: 'united-states',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [{ alias: 'General Mills' }],
  },
  {
    slug: 'mars',
    kind: 'company',
    name: 'Mars, Incorporated',
    description: 'Privately held group across confectionery, pet care and food.',
    officialDomain: 'mars.com',
    hq: 'united-states',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [
      { alias: 'Mars, Incorporated' },
      { alias: 'Mars', requiresContext: true },
      { alias: 'Mars Wrigley', type: 'brand' },
    ],
  },
  {
    slug: 'ferrero',
    kind: 'company',
    name: 'Ferrero',
    description: 'Italian confectionery group.',
    officialDomain: 'ferrero.com',
    hq: 'italy',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [
      { alias: 'Ferrero' },
      { alias: 'Ferrero Group', type: 'legal' },
      { alias: 'Nutella', type: 'brand' },
    ],
  },
  {
    slug: 'hormel-foods',
    kind: 'company',
    name: 'Hormel Foods',
    description: 'United States packaged and protein food company.',
    officialDomain: 'hormelfoods.com',
    ticker: 'HRL',
    hq: 'united-states',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [{ alias: 'Hormel Foods' }, { alias: 'Hormel' }],
  },
  {
    slug: 'cargill',
    kind: 'company',
    name: 'Cargill',
    description: 'Privately held agricultural commodities, food ingredients and trading group.',
    officialDomain: 'cargill.com',
    hq: 'united-states',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage', 'logistics'],
    aliases: [{ alias: 'Cargill' }, { alias: 'Cargill, Incorporated', type: 'legal' }],
  },
  {
    slug: 'sysco',
    kind: 'company',
    name: 'Sysco',
    description: 'Foodservice distribution group supplying restaurants and institutional kitchens.',
    officialDomain: 'sysco.com',
    ticker: 'SYY',
    hq: 'united-states',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage', 'logistics'],
    aliases: [{ alias: 'Sysco' }],
  },
  {
    slug: 'lavazza',
    kind: 'company',
    name: 'Lavazza',
    description: 'Italian coffee roaster and beverage group.',
    officialDomain: 'lavazzagroup.com',
    hq: 'italy',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [{ alias: 'Lavazza' }, { alias: 'Luigi Lavazza S.p.A.', type: 'legal' }],
  },
  {
    slug: 'keurig-dr-pepper',
    kind: 'company',
    name: 'Keurig Dr Pepper',
    description: 'Beverage group across coffee systems and carbonated soft drinks.',
    officialDomain: 'keurigdrpepper.com',
    ticker: 'KDP',
    hq: 'united-states',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [
      { alias: 'Keurig Dr Pepper' },
      { alias: 'KDP', type: 'abbreviation', requiresContext: true },
    ],
  },
  {
    slug: 'tetra-pak',
    kind: 'company',
    name: 'Tetra Pak',
    description: 'Food processing and packaging systems supplier.',
    officialDomain: 'tetrapak.com',
    hq: 'switzerland',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'industrial-manufacturing'],
    aliases: [{ alias: 'Tetra Pak' }, { alias: 'Tetra Laval' }],
  },
  {
    slug: 'valio',
    kind: 'company',
    name: 'Valio',
    description: 'Finnish dairy cooperative and food company.',
    officialDomain: 'valio.com',
    hq: 'finland',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [{ alias: 'Valio' }],
  },

  // ── Beer, wine and spirits ────────────────────────────────────────────────
  {
    slug: 'diageo',
    kind: 'company',
    name: 'Diageo',
    description: 'Premium drinks group across spirits and beer.',
    officialDomain: 'diageo.com',
    ticker: 'DGE',
    hq: 'united-kingdom',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [{ alias: 'Diageo' }, { alias: 'Guinness', type: 'brand' }],
  },
  {
    slug: 'heineken',
    kind: 'company',
    name: 'Heineken',
    description: 'Dutch brewing group operating internationally.',
    officialDomain: 'theheinekencompany.com',
    ticker: 'HEIA',
    hq: 'netherlands',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [{ alias: 'Heineken' }, { alias: 'Heineken N.V.', type: 'legal' }],
  },
  {
    slug: 'carlsberg',
    kind: 'company',
    name: 'Carlsberg Group',
    description: 'Danish brewing group.',
    officialDomain: 'carlsberggroup.com',
    ticker: 'CARL-B',
    hq: 'denmark',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [{ alias: 'Carlsberg Group' }, { alias: 'Carlsberg' }],
  },
  {
    slug: 'molson-coors',
    kind: 'company',
    name: 'Molson Coors',
    description: 'North American and European brewing group.',
    officialDomain: 'molsoncoors.com',
    ticker: 'TAP',
    hq: 'united-states',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [{ alias: 'Molson Coors' }, { alias: 'Molson Coors Beverage Company', type: 'legal' }],
  },
  {
    slug: 'pernod-ricard',
    kind: 'company',
    name: 'Pernod Ricard',
    description: 'French wines and spirits group.',
    officialDomain: 'pernod-ricard.com',
    ticker: 'RI',
    hq: 'france',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [{ alias: 'Pernod Ricard' }],
  },
  {
    slug: 'campari-group',
    kind: 'company',
    name: 'Campari Group',
    // Redomiciled to the Netherlands in 2020; this is the name it files under.
    legalName: 'Davide Campari-Milano N.V.',
    description: 'Italian spirits and aperitif group.',
    officialDomain: 'camparigroup.com',
    ticker: 'CPR',
    hq: 'italy',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [{ alias: 'Campari Group' }, { alias: 'Davide Campari-Milano', type: 'legal' }],
  },

  // ── Beauty, personal and home care ────────────────────────────────────────
  {
    slug: 'loreal',
    kind: 'company',
    name: "L'Oréal",
    description:
      'French beauty group across consumer, luxury, professional and dermatological divisions.',
    officialDomain: 'loreal.com',
    ticker: 'OR',
    hq: 'france',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods'],
    aliases: [{ alias: "L'Oréal" }, { alias: 'LOreal' }, { alias: 'Loreal' }],
  },
  {
    slug: 'estee-lauder',
    kind: 'company',
    name: 'The Estée Lauder Companies',
    description: 'Prestige beauty group across skincare, makeup, fragrance and hair care.',
    officialDomain: 'elcompanies.com',
    ticker: 'EL',
    hq: 'united-states',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods'],
    aliases: [
      { alias: 'Estée Lauder' },
      { alias: 'Estee Lauder' },
      { alias: 'The Estée Lauder Companies', type: 'legal' },
    ],
  },
  {
    slug: 'coty',
    kind: 'company',
    name: 'Coty',
    description: 'Beauty group across fragrance and cosmetics, largely licence-based.',
    officialDomain: 'coty.com',
    ticker: 'COTY',
    hq: 'united-states',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods'],
    aliases: [{ alias: 'Coty' }, { alias: 'Coty Inc.', type: 'legal' }],
  },
  {
    slug: 'henkel',
    kind: 'company',
    name: 'Henkel',
    description:
      'German group across adhesive technologies and consumer brands in laundry, home and beauty care.',
    officialDomain: 'henkel.com',
    ticker: 'HEN3',
    hq: 'germany',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'industrial-manufacturing'],
    aliases: [{ alias: 'Henkel' }, { alias: 'Henkel AG & Co. KGaA', type: 'legal' }],
  },
  {
    slug: 'clorox',
    kind: 'company',
    name: 'The Clorox Company',
    description: 'Household cleaning and consumer products group.',
    officialDomain: 'thecloroxcompany.com',
    ticker: 'CLX',
    hq: 'united-states',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods'],
    aliases: [{ alias: 'Clorox' }, { alias: 'The Clorox Company', type: 'legal' }],
  },
  {
    slug: 'ecolab',
    kind: 'company',
    name: 'Ecolab',
    description:
      'Water, hygiene and infection-prevention products and services for industry and hospitality.',
    officialDomain: 'ecolab.com',
    ticker: 'ECL',
    hq: 'united-states',
    primaryIndustrySlug: 'industrial-manufacturing',
    industrySlugs: ['industrial-manufacturing', 'consumer-goods', 'travel'],
    aliases: [{ alias: 'Ecolab' }, { alias: 'Ecolab Inc.', type: 'legal' }],
  },

  // ── Adjacent sectors ──────────────────────────────────────────────────────
  {
    slug: 'telstra',
    kind: 'company',
    name: 'Telstra',
    description: 'Australian telecommunications and technology group.',
    officialDomain: 'telstra.com.au',
    ticker: 'TLS',
    hq: 'australia',
    primaryIndustrySlug: 'telecommunications',
    industrySlugs: ['telecommunications'],
    aliases: [{ alias: 'Telstra' }, { alias: 'Telstra Group', type: 'legal' }],
  },
  {
    slug: 'stellantis',
    kind: 'company',
    name: 'Stellantis',
    description: 'Multinational automotive manufacturer formed from the FCA and PSA merger.',
    officialDomain: 'stellantis.com',
    ticker: 'STLA',
    hq: 'netherlands',
    primaryIndustrySlug: 'automotive',
    industrySlugs: ['automotive'],
    aliases: [{ alias: 'Stellantis' }, { alias: 'Stellantis N.V.', type: 'legal' }],
  },
  {
    slug: 'jab-holding',
    kind: 'company',
    name: 'JAB Holding Company',
    description: 'Investment group with consumer, coffee and pet-care holdings.',
    officialDomain: 'jabholco.com',
    hq: 'luxembourg',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'financial-services'],
    aliases: [
      { alias: 'JAB Holding Company' },
      { alias: 'JAB Holding' },
      { alias: 'JAB', type: 'abbreviation', requiresContext: true },
    ],
  },

  /*
   * ── DACH retail and luxury, added 2026-09-04 ──────────────────────────────
   *
   * The company list was Anglo-American with a few European names bolted on, which is
   * why searching Breuninger returned nothing: it was never registered. Migros and Coop
   * were registered and still returned nothing, which was the other half of the problem
   * — no source in the registry published in German or covered Switzerland at all.
   *
   * Luxury is here as its own sector rather than folded into fashion. A watch maison and
   * a fast-fashion retailer are not in the same business: one manages scarcity on
   * purpose and barely discounts, the other lives on markdown rate.
   */

  // ── German retail ─────────────────────────────────────────────────────────
  {
    slug: 'breuninger',
    kind: 'company',
    name: 'Breuninger',
    legalName: 'E. Breuninger GmbH & Co.',
    description:
      'German premium department store group and online retailer, strongest in the south, positioned between mainstream apparel retail and luxury.',
    officialDomain: 'breuninger.com',
    hq: 'germany',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'retail', 'luxury-goods'],
    aliases: [{ alias: 'Breuninger' }, { alias: 'E. Breuninger GmbH & Co.', type: 'legal' }],
  },
  {
    slug: 'edeka',
    kind: 'company',
    name: 'Edeka',
    description:
      'Germany’s largest grocery cooperative, operating a federated structure of regional companies and independent retailers.',
    officialDomain: 'edeka.de',
    hq: 'germany',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    aliases: [{ alias: 'Edeka' }, { alias: 'EDEKA Zentrale', type: 'legal' }],
  },
  {
    slug: 'otto-group',
    kind: 'company',
    name: 'Otto Group',
    description:
      'Hamburg-based retail and commerce group, one of the largest European online retailers outside the marketplaces.',
    officialDomain: 'ottogroup.com',
    hq: 'germany',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'fashion-apparel'],
    aliases: [
      { alias: 'Otto Group' },
      // "Otto" alone is a given name and a common word in German text.
      { alias: 'Otto', requiresContext: true },
    ],
  },
  {
    slug: 'metro-ag',
    kind: 'company',
    name: 'Metro AG',
    description: 'German wholesale group serving hospitality and independent retail across Europe.',
    officialDomain: 'metroag.de',
    hq: 'germany',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    aliases: [{ alias: 'Metro AG' }, { alias: 'Metro', requiresContext: true }],
  },
  {
    slug: 'dm-drogerie-markt',
    kind: 'company',
    name: 'dm-drogerie markt',
    description: 'German drugstore chain, the largest in the DACH region by store count.',
    officialDomain: 'dm.de',
    hq: 'germany',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    aliases: [
      { alias: 'dm-drogerie markt' },
      { alias: 'dm drogerie markt' },
      // Two letters, and a word in several languages.
      { alias: 'dm', requiresContext: true },
    ],
  },
  {
    slug: 'rossmann',
    kind: 'company',
    name: 'Rossmann',
    description: 'German drugstore chain competing with dm across Germany and eastern Europe.',
    officialDomain: 'rossmann.de',
    hq: 'germany',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    aliases: [{ alias: 'Rossmann' }, { alias: 'Dirk Rossmann GmbH', type: 'legal' }],
  },
  {
    slug: 'douglas',
    kind: 'company',
    name: 'Douglas',
    description: 'European beauty retailer, listed in Frankfurt, operating stores and online.',
    officialDomain: 'douglas.de',
    hq: 'germany',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    aliases: [
      { alias: 'Douglas', requiresContext: true },
      { alias: 'Douglas AG', type: 'legal' },
    ],
  },
  {
    slug: 'puma',
    kind: 'company',
    name: 'Puma',
    description:
      'German sportswear brand, third by revenue in the European sports market behind adidas and Nike.',
    officialDomain: 'puma.com',
    ticker: 'PUM',
    hq: 'germany',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'consumer-goods'],
    aliases: [{ alias: 'Puma' }, { alias: 'Puma SE', type: 'legal' }],
  },

  // ── Luxury and watches ────────────────────────────────────────────────────
  {
    slug: 'rolex',
    kind: 'company',
    name: 'Rolex',
    description:
      'Swiss watch manufacturer held by a private foundation, the largest by value in Swiss watchmaking and unusual in publishing almost nothing about itself.',
    officialDomain: 'rolex.com',
    hq: 'switzerland',
    primaryIndustrySlug: 'luxury-goods',
    industrySlugs: ['luxury-goods'],
    aliases: [{ alias: 'Rolex' }, { alias: 'Rolex SA', type: 'legal' }],
  },
  {
    slug: 'richemont',
    kind: 'company',
    name: 'Richemont',
    legalName: 'Compagnie Financière Richemont SA',
    description:
      'Swiss luxury group holding Cartier, Van Cleef & Arpels, IWC, Jaeger-LeCoultre and others, plus online distribution.',
    officialDomain: 'richemont.com',
    ticker: 'CFR',
    hq: 'switzerland',
    primaryIndustrySlug: 'luxury-goods',
    industrySlugs: ['luxury-goods', 'retail'],
    aliases: [
      { alias: 'Richemont' },
      { alias: 'Compagnie Financière Richemont', type: 'legal' },
      { alias: 'Cartier' },
      { alias: 'Van Cleef & Arpels' },
      { alias: 'IWC', requiresContext: true },
      { alias: 'Jaeger-LeCoultre' },
    ],
  },
  {
    slug: 'bucherer',
    kind: 'company',
    name: 'Bucherer',
    description:
      'Swiss luxury watch and jewellery retailer, the largest authorised dealer network in Europe; acquired by Rolex in 2023.',
    officialDomain: 'bucherer.com',
    hq: 'switzerland',
    primaryIndustrySlug: 'luxury-goods',
    industrySlugs: ['luxury-goods', 'retail'],
    aliases: [{ alias: 'Bucherer' }, { alias: 'Carl F. Bucherer' }],
  },
  {
    slug: 'swatch-group',
    kind: 'company',
    name: 'Swatch Group',
    description:
      'Swiss watch group spanning Omega, Longines, Tissot and Swatch, and a major supplier of movements to the wider industry.',
    officialDomain: 'swatchgroup.com',
    ticker: 'UHR',
    hq: 'switzerland',
    primaryIndustrySlug: 'luxury-goods',
    industrySlugs: ['luxury-goods', 'consumer-goods'],
    aliases: [
      { alias: 'Swatch Group' },
      { alias: 'Swatch', requiresContext: true },
      { alias: 'Omega', requiresContext: true },
      { alias: 'Longines' },
      { alias: 'Tissot' },
    ],
  },
  {
    slug: 'lvmh',
    kind: 'company',
    name: 'LVMH',
    legalName: 'LVMH Moët Hennessy Louis Vuitton SE',
    description:
      'The largest luxury group, spanning fashion and leather goods, watches and jewellery, wines and spirits, and selective retail.',
    officialDomain: 'lvmh.com',
    ticker: 'MC',
    hq: 'france',
    primaryIndustrySlug: 'luxury-goods',
    industrySlugs: ['luxury-goods', 'fashion-apparel', 'retail'],
    aliases: [
      { alias: 'LVMH' },
      { alias: 'Moët Hennessy Louis Vuitton', type: 'legal' },
      { alias: 'Louis Vuitton' },
      { alias: 'Tiffany & Co.' },
      { alias: 'Sephora' },
      { alias: 'Bulgari' },
    ],
  },
  {
    slug: 'kering',
    kind: 'company',
    name: 'Kering',
    description: 'French luxury group holding Gucci, Saint Laurent, Bottega Veneta and Boucheron.',
    officialDomain: 'kering.com',
    ticker: 'KER',
    hq: 'france',
    primaryIndustrySlug: 'luxury-goods',
    industrySlugs: ['luxury-goods', 'fashion-apparel'],
    aliases: [
      { alias: 'Kering' },
      { alias: 'Gucci' },
      { alias: 'Saint Laurent' },
      { alias: 'Bottega Veneta' },
    ],
  },
  {
    slug: 'hermes',
    kind: 'company',
    name: 'Hermès',
    legalName: 'Hermès International',
    description:
      'French luxury house, family-controlled, known for leather goods and for deliberately constrained production.',
    officialDomain: 'hermes.com',
    ticker: 'RMS',
    hq: 'france',
    primaryIndustrySlug: 'luxury-goods',
    industrySlugs: ['luxury-goods', 'fashion-apparel'],
    aliases: [{ alias: 'Hermès' }, { alias: 'Hermes' }],
  },
  {
    slug: 'patek-philippe',
    kind: 'company',
    name: 'Patek Philippe',
    description:
      'Independent Genevan watch manufacturer, family-owned, at the top of the Swiss watch market by price.',
    officialDomain: 'patek.com',
    hq: 'switzerland',
    primaryIndustrySlug: 'luxury-goods',
    industrySlugs: ['luxury-goods'],
    aliases: [{ alias: 'Patek Philippe' }, { alias: 'Patek' }],
  },
  {
    slug: 'audemars-piguet',
    kind: 'company',
    name: 'Audemars Piguet',
    description:
      'Independent Swiss watch manufacturer from the Vallée de Joux, selling largely through its own boutiques.',
    officialDomain: 'audemarspiguet.com',
    hq: 'switzerland',
    primaryIndustrySlug: 'luxury-goods',
    industrySlugs: ['luxury-goods'],
    aliases: [{ alias: 'Audemars Piguet' }, { alias: 'Audemars' }],
  },

  /*
   * ── Benelux and the Nordics, added 2026-09-04 ─────────────────────────────
   *
   * Measured before adding: not one of Ahold Delhaize, Albert Heijn, Jumbo, Colruyt,
   * HEMA, Adyen, Philips, IKEA, Ericsson, Nokia, Novo Nordisk, Maersk, Lego, Vestas,
   * Equinor or Kesko was a tracked entity, and the taxonomy held Sweden but neither the
   * Netherlands, Belgium, Denmark, Norway nor Finland.
   *
   * Colruyt and HEMA were already turning up in claims — RetailDetail and ESM cover
   * Benelux grocery — so the articles were arriving and there was no company for them to
   * attach to. That is the worst version of this problem: the evidence is in the corpus
   * and unreachable by name.
   */

  // ── Netherlands and Belgium ───────────────────────────────────────────────
  {
    slug: 'ahold-delhaize',
    kind: 'company',
    name: 'Ahold Delhaize',
    legalName: 'Koninklijke Ahold Delhaize N.V.',
    description:
      'Dutch-Belgian grocery group operating Albert Heijn, Delhaize, bol and a large US store portfolio.',
    officialDomain: 'aholddelhaize.com',
    ticker: 'AD',
    hq: 'netherlands',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    aliases: [
      { alias: 'Ahold Delhaize' },
      { alias: 'Koninklijke Ahold Delhaize', type: 'legal' },
      { alias: 'Ahold' },
      { alias: 'Delhaize' },
      { alias: 'Albert Heijn' },
    ],
  },
  {
    slug: 'jumbo',
    kind: 'company',
    name: 'Jumbo',
    description: 'Dutch family-owned grocery chain, second largest in the Netherlands.',
    officialDomain: 'jumborapportage.com',
    hq: 'netherlands',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    // "Jumbo" is an ordinary adjective in English retail copy.
    aliases: [{ alias: 'Jumbo', requiresContext: true }, { alias: 'Jumbo Supermarkten' }],
  },
  {
    slug: 'colruyt',
    kind: 'company',
    name: 'Colruyt Group',
    description:
      'Belgian retail group built on a lowest-price guarantee, with grocery, wholesale and foodservice formats.',
    officialDomain: 'colruytgroup.com',
    ticker: 'COLR',
    hq: 'belgium',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    aliases: [{ alias: 'Colruyt' }, { alias: 'Colruyt Group' }],
  },
  {
    slug: 'hema',
    kind: 'company',
    name: 'HEMA',
    description: 'Dutch variety retailer selling own-brand household goods, food and clothing.',
    officialDomain: 'hema.com',
    hq: 'netherlands',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    // Four letters and a common prefix in medical text.
    aliases: [{ alias: 'HEMA', requiresContext: true }],
  },
  {
    slug: 'heineken',
    kind: 'company',
    name: 'Heineken',
    legalName: 'Heineken N.V.',
    description: 'Dutch brewing group, second largest brewer worldwide by volume.',
    officialDomain: 'theheinekencompany.com',
    ticker: 'HEIA',
    hq: 'netherlands',
    primaryIndustrySlug: 'food-beverage',
    industrySlugs: ['food-beverage', 'consumer-goods'],
    aliases: [{ alias: 'Heineken' }, { alias: 'Heineken N.V.', type: 'legal' }],
  },
  {
    slug: 'philips',
    kind: 'company',
    name: 'Philips',
    legalName: 'Koninklijke Philips N.V.',
    description:
      'Dutch health technology company, now focused on diagnostic imaging and personal health after exiting lighting and consumer electronics.',
    officialDomain: 'philips.com',
    ticker: 'PHIA',
    hq: 'netherlands',
    primaryIndustrySlug: 'healthcare',
    industrySlugs: ['healthcare', 'consumer-goods', 'industrial-manufacturing'],
    aliases: [{ alias: 'Philips' }, { alias: 'Koninklijke Philips', type: 'legal' }],
  },
  {
    slug: 'adyen',
    kind: 'company',
    name: 'Adyen',
    description:
      'Dutch payments platform serving large merchants on a single global processing stack.',
    officialDomain: 'adyen.com',
    ticker: 'ADYEN',
    hq: 'netherlands',
    primaryIndustrySlug: 'financial-services',
    industrySlugs: ['financial-services', 'technology-ai', 'retail'],
    aliases: [{ alias: 'Adyen' }],
  },

  // ── Nordics ───────────────────────────────────────────────────────────────
  {
    slug: 'ikea',
    kind: 'company',
    name: 'IKEA',
    description:
      'Swedish-founded home furnishing retailer, operated by Ingka Group under franchise from Inter IKEA.',
    officialDomain: 'ikea.com',
    hq: 'sweden',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    aliases: [{ alias: 'IKEA' }, { alias: 'Ingka Group' }, { alias: 'Inter IKEA' }],
  },
  {
    slug: 'salling-group',
    kind: 'company',
    name: 'Salling Group',
    description:
      'Denmark’s largest retailer, operating Netto, Føtex and Bilka, owned by a charitable foundation.',
    officialDomain: 'sallinggroup.com',
    hq: 'denmark',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    aliases: [
      { alias: 'Salling Group' },
      { alias: 'Netto', requiresContext: true },
      { alias: 'Bilka' },
    ],
  },
  {
    slug: 'kesko',
    kind: 'company',
    name: 'Kesko',
    description: 'Finnish trading group spanning grocery, building supplies and car trade.',
    officialDomain: 'kesko.fi',
    ticker: 'KESKOB',
    hq: 'finland',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    aliases: [{ alias: 'Kesko' }, { alias: 'K-Group' }],
  },
  {
    slug: 'reitan',
    kind: 'company',
    name: 'Reitan',
    description:
      'Norwegian family-owned retail group operating REMA 1000 grocery discount and convenience formats across the Nordics.',
    officialDomain: 'reitan.no',
    hq: 'norway',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    aliases: [{ alias: 'Reitan' }, { alias: 'REMA 1000' }],
  },
  {
    slug: 'orkla',
    kind: 'company',
    name: 'Orkla',
    description: 'Norwegian branded consumer goods group, strongest in Nordic food and household.',
    officialDomain: 'orkla.com',
    ticker: 'ORK',
    hq: 'norway',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    aliases: [{ alias: 'Orkla' }],
  },
  {
    slug: 'carlsberg',
    kind: 'company',
    name: 'Carlsberg',
    description: 'Danish brewing group with a large western European and Asian portfolio.',
    officialDomain: 'carlsberggroup.com',
    ticker: 'CARL-B',
    hq: 'denmark',
    primaryIndustrySlug: 'food-beverage',
    industrySlugs: ['food-beverage', 'consumer-goods'],
    aliases: [{ alias: 'Carlsberg' }, { alias: 'Carlsberg Group' }],
  },
  {
    slug: 'lego',
    kind: 'company',
    name: 'LEGO',
    legalName: 'LEGO A/S',
    description: 'Danish family-owned toy manufacturer and retailer.',
    officialDomain: 'lego.com',
    hq: 'denmark',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'retail'],
    aliases: [{ alias: 'LEGO' }, { alias: 'LEGO Group' }],
  },
  {
    slug: 'bestseller',
    kind: 'company',
    name: 'Bestseller',
    legalName: 'BESTSELLER A/S',
    // Danish CVR. Verified against the register: 31 filings, the newest for the year
    // ending 2025-07-31 reporting DKK 38.07bn of consolidated revenue and 21,638 staff.
    registrationNumber: '88216512',
    description:
      'Danish family-owned fashion group behind Jack & Jones, Vero Moda and Only, and a major Zalando shareholder.',
    officialDomain: 'bestseller.com',
    hq: 'denmark',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'retail'],
    // An ordinary noun in publishing and retail copy.
    aliases: [
      { alias: 'Bestseller', requiresContext: true },
      { alias: 'Jack & Jones' },
      { alias: 'Vero Moda' },
    ],
  },
  {
    slug: 'maersk',
    kind: 'company',
    name: 'Maersk',
    legalName: 'A.P. Møller – Mærsk A/S',
    description:
      'Danish container shipping and integrated logistics group; its rates and routings are a leading indicator for retail supply chains.',
    officialDomain: 'maersk.com',
    ticker: 'MAERSK-B',
    hq: 'denmark',
    primaryIndustrySlug: 'logistics',
    industrySlugs: ['logistics', 'retail'],
    aliases: [{ alias: 'Maersk' }, { alias: 'Mærsk' }, { alias: 'A.P. Moller', type: 'legal' }],
  },
  {
    slug: 'novo-nordisk',
    kind: 'company',
    name: 'Novo Nordisk',
    description:
      'Danish pharmaceutical company in diabetes and obesity care; its GLP-1 products are reshaping food and grocery demand.',
    officialDomain: 'novonordisk.com',
    ticker: 'NOVO-B',
    hq: 'denmark',
    primaryIndustrySlug: 'pharmaceuticals',
    industrySlugs: ['pharmaceuticals', 'consumer-goods'],
    aliases: [{ alias: 'Novo Nordisk' }, { alias: 'Ozempic' }, { alias: 'Wegovy' }],
  },
  {
    slug: 'ericsson',
    kind: 'company',
    name: 'Ericsson',
    legalName: 'Telefonaktiebolaget LM Ericsson',
    description: 'Swedish networking and telecommunications equipment vendor.',
    officialDomain: 'ericsson.com',
    ticker: 'ERIC-B',
    hq: 'sweden',
    primaryIndustrySlug: 'telecommunications',
    industrySlugs: ['telecommunications', 'technology-ai'],
    aliases: [{ alias: 'Ericsson' }, { alias: 'Telefonaktiebolaget LM Ericsson', type: 'legal' }],
  },
  {
    slug: 'nokia',
    kind: 'company',
    name: 'Nokia',
    description: 'Finnish network infrastructure vendor.',
    officialDomain: 'nokia.com',
    ticker: 'NOKIA',
    hq: 'finland',
    primaryIndustrySlug: 'telecommunications',
    industrySlugs: ['telecommunications', 'technology-ai'],
    aliases: [{ alias: 'Nokia' }],
  },

  // ── Retail, fashion and consumer goods, added after a coverage gap review ──
  //
  // A colleague asked why Primark was missing. It was, and so were most of the
  // companies a European retail practice would reach for first. The list below was
  // chosen from two signals rather than taste: names the corpus already mentions but
  // could not resolve, and the largest absences in the sectors this product covers.
  //
  // Mentions were counted on word boundaries, not substrings, which mattered more than
  // expected: "Action" looked like 34 claims and was one — the rest were the ordinary
  // English word. "Normal" was four and is none.
  //
  // Legal names are taken from the ESEF filing index where the company files there, so
  // the financial connectors resolve them on their registered name rather than guessing.
  {
    slug: 'tesco',
    kind: 'company',
    name: 'Tesco',
    legalName: 'Tesco PLC',
    description:
      "Britain's largest grocer, running superstores, convenience and a mature online grocery operation.",
    officialDomain: 'tescoplc.com',
    ticker: 'TSCO',
    hq: 'united-kingdom',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'Tesco' },
      { alias: 'Tesco PLC', type: 'legal' },
      { alias: 'Tesco Express' },
      { alias: 'Tesco Extra' },
    ],
  },
  {
    slug: 'sainsburys',
    kind: 'company',
    name: "Sainsbury's",
    legalName: 'J Sainsbury plc',
    description: 'UK grocery and general merchandise group, owner of Argos and Habitat.',
    officialDomain: 'about.sainsburys.co.uk',
    ticker: 'SBRY',
    hq: 'united-kingdom',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: "Sainsbury's" },
      { alias: 'J Sainsbury', type: 'legal' },
      { alias: 'Sainsburys' },
      { alias: 'Argos' },
    ],
  },
  {
    slug: 'carrefour',
    kind: 'company',
    name: 'Carrefour',
    legalName: 'Carrefour SA',
    description:
      'French hypermarket pioneer operating across Europe and Latin America under several store formats.',
    officialDomain: 'carrefour.com',
    ticker: 'CA',
    hq: 'france',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [{ alias: 'Carrefour' }, { alias: 'Carrefour SA', type: 'legal' }],
  },
  {
    slug: 'mercadona',
    kind: 'company',
    name: 'Mercadona',
    description:
      'Spanish supermarket leader, privately held, built on a narrow own-label assortment.',
    officialDomain: 'mercadona.es',
    hq: 'spain',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    businessModelSlug: 'vertical-retail',
    aliases: [{ alias: 'Mercadona' }],
  },
  {
    slug: 'auchan',
    kind: 'company',
    name: 'Auchan',
    legalName: 'Auchan Retail',
    description:
      'French family-controlled hypermarket group with a large central and eastern European estate.',
    officialDomain: 'auchan-retail.com',
    hq: 'france',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [{ alias: 'Auchan' }, { alias: 'Auchan Retail', type: 'legal' }],
  },
  {
    slug: 'norgesgruppen',
    kind: 'company',
    name: 'NorgesGruppen',
    legalName: 'NorgesGruppen ASA',
    description: 'Norway’s largest grocery group, operating Kiwi, Meny and Spar Norge.',
    officialDomain: 'norgesgruppen.no',
    hq: 'norway',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'NorgesGruppen' },
      { alias: 'NorgesGruppen ASA', type: 'legal' },
      { alias: 'Kiwi' },
      { alias: 'Meny' },
    ],
  },
  {
    slug: 'ica-gruppen',
    kind: 'company',
    name: 'ICA Gruppen',
    legalName: 'ICA Gruppen AB',
    description:
      'Swedish grocery group run as a retailer-owned federation of independently operated stores.',
    officialDomain: 'icagruppen.se',
    hq: 'sweden',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'ICA Gruppen' },
      { alias: 'ICA Gruppen AB', type: 'legal' },
      { alias: 'ICA' },
    ],
  },
  {
    slug: 'axfood',
    kind: 'company',
    name: 'Axfood',
    legalName: 'Axfood AB',
    description: 'Swedish food retailer behind Willys and Hemköp.',
    officialDomain: 'axfood.com',
    ticker: 'AXFO',
    hq: 'sweden',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'Axfood' },
      { alias: 'Axfood AB', type: 'legal' },
      { alias: 'Willys' },
      { alias: 'Hemköp' },
    ],
  },
  {
    slug: 'spar-international',
    kind: 'company',
    name: 'SPAR International',
    description:
      'Voluntary federation of independently owned national SPAR organisations; no single operating company sits behind the brand.',
    officialDomain: 'spar-international.com',
    hq: 'netherlands',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'food-beverage'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'SPAR International' },
      { alias: 'SPAR', requiresContext: true },
      { alias: 'Spar Österreich' },
    ],
  },
  {
    slug: 'target',
    kind: 'company',
    name: 'Target',
    legalName: 'Target Corporation',
    description: 'US general merchandise retailer positioned on design-led own brands.',
    officialDomain: 'target.com',
    ticker: 'TGT',
    hq: 'united-states',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'Target Corporation', type: 'legal' },
      { alias: 'Target', requiresContext: true },
    ],
  },
  {
    slug: 'action-retail',
    kind: 'company',
    name: 'Action',
    legalName: 'Action Holding B.V.',
    description:
      'Dutch non-food discounter, the fastest-growing retailer in Europe by store openings.',
    officialDomain: 'action.com',
    hq: 'netherlands',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [{ alias: 'Action Holding', type: 'legal' }, { alias: 'Action Nederland' }],
  },
  {
    slug: 'primark',
    kind: 'company',
    name: 'Primark',
    legalName: 'Primark Limited',
    description:
      'Irish value fashion retailer trading as Penneys at home; a division of Associated British Foods rather than a separate filer, so no accounts of its own are published.',
    officialDomain: 'primark.com',
    hq: 'ireland',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'retail'],
    businessModelSlug: 'fast-fashion',
    aliases: [
      { alias: 'Primark' },
      { alias: 'Primark Limited', type: 'legal' },
      { alias: 'Penneys' },
    ],
  },
  {
    slug: 'associated-british-foods',
    kind: 'company',
    name: 'Associated British Foods',
    legalName: 'Associated British Foods plc',
    description:
      'UK group combining sugar, grocery brands, ingredients and agriculture with Primark; the listed parent whose accounts cover all of them together.',
    officialDomain: 'abf.co.uk',
    ticker: 'ABF',
    hq: 'united-kingdom',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage', 'fashion-apparel'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'Associated British Foods' },
      { alias: 'Associated British Foods plc', type: 'legal' },
      { alias: 'ABF', requiresContext: true },
    ],
  },
  {
    slug: 'next-plc',
    kind: 'company',
    name: 'Next',
    legalName: 'Next plc',
    description:
      'UK clothing and homeware retailer whose Total Platform sells and distributes for third-party brands.',
    officialDomain: 'nextplc.co.uk',
    ticker: 'NXT',
    hq: 'united-kingdom',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'retail'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'Next plc', type: 'legal' },
      { alias: 'Next Retail' },
      { alias: 'Total Platform' },
    ],
  },
  {
    slug: 'marks-and-spencer',
    kind: 'company',
    name: 'Marks & Spencer',
    legalName: 'Marks and Spencer Group p.l.c.',
    description:
      'UK retailer pairing own-brand clothing and homeware with a premium food business.',
    officialDomain: 'marksandspencer.com',
    ticker: 'MKS',
    hq: 'united-kingdom',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'fashion-apparel', 'food-beverage'],
    businessModelSlug: 'vertical-retail',
    aliases: [
      { alias: 'Marks & Spencer' },
      { alias: 'Marks and Spencer Group', type: 'legal' },
      { alias: 'M&S', requiresContext: true },
    ],
  },
  {
    slug: 'asos',
    kind: 'company',
    name: 'ASOS',
    legalName: 'ASOS Plc',
    description:
      'UK online fashion retailer selling own and third-party brands to a young global market.',
    officialDomain: 'asosplc.com',
    ticker: 'ASC',
    hq: 'united-kingdom',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'retail'],
    businessModelSlug: 'ultra-fast-digital',
    aliases: [{ alias: 'ASOS' }, { alias: 'ASOS Plc', type: 'legal' }],
  },
  {
    slug: 'jd-sports',
    kind: 'company',
    name: 'JD Sports',
    legalName: 'JD Sports Fashion plc',
    description:
      'UK sports fashion retailer and one of the largest wholesale customers of Nike and adidas.',
    officialDomain: 'jdplc.com',
    ticker: 'JD',
    hq: 'united-kingdom',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'fashion-apparel'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'JD Sports' },
      { alias: 'JD Sports Fashion', type: 'legal' },
      { alias: 'JD Group' },
    ],
  },
  {
    slug: 'mango',
    kind: 'company',
    name: 'Mango',
    legalName: 'Punto Fa, S.L.',
    description:
      'Spanish family-owned fashion retailer, privately held and expanding outside Europe.',
    officialDomain: 'mango.com',
    hq: 'spain',
    primaryIndustrySlug: 'fashion-apparel',
    industrySlugs: ['fashion-apparel', 'retail'],
    businessModelSlug: 'fast-fashion',
    aliases: [{ alias: 'Mango' }, { alias: 'Punto Fa', type: 'legal' }],
  },
  {
    slug: 'decathlon',
    kind: 'company',
    name: 'Decathlon',
    legalName: 'Decathlon SE',
    description:
      'French sporting goods retailer designing and manufacturing most of what it sells under its own brands.',
    officialDomain: 'decathlon.com',
    hq: 'france',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'fashion-apparel', 'consumer-goods'],
    businessModelSlug: 'vertical-retail',
    aliases: [{ alias: 'Decathlon' }, { alias: 'Decathlon SE', type: 'legal' }],
  },
  {
    slug: 'burberry',
    kind: 'company',
    name: 'Burberry',
    legalName: 'Burberry Group plc',
    description: 'British luxury house best known for outerwear and its check pattern.',
    officialDomain: 'burberryplc.com',
    ticker: 'BRBY',
    hq: 'united-kingdom',
    primaryIndustrySlug: 'luxury-goods',
    industrySlugs: ['luxury-goods', 'fashion-apparel'],
    businessModelSlug: 'premium-brand',
    aliases: [{ alias: 'Burberry' }, { alias: 'Burberry Group', type: 'legal' }],
  },
  {
    slug: 'moncler',
    kind: 'company',
    name: 'Moncler',
    legalName: 'Moncler S.p.A.',
    description: 'Italian luxury outerwear group, owner of Stone Island.',
    officialDomain: 'monclergroup.com',
    ticker: 'MONC',
    hq: 'italy',
    primaryIndustrySlug: 'luxury-goods',
    industrySlugs: ['luxury-goods', 'fashion-apparel'],
    businessModelSlug: 'premium-brand',
    aliases: [
      { alias: 'Moncler' },
      { alias: 'Moncler S.p.A.', type: 'legal' },
      { alias: 'Stone Island' },
    ],
  },
  {
    slug: 'prada',
    kind: 'company',
    name: 'Prada',
    legalName: 'Prada S.p.A.',
    description: 'Italian luxury group behind Prada, Miu Miu and Church’s, listed in Hong Kong.',
    officialDomain: 'pradagroup.com',
    ticker: '1913',
    hq: 'italy',
    primaryIndustrySlug: 'luxury-goods',
    industrySlugs: ['luxury-goods', 'fashion-apparel'],
    businessModelSlug: 'premium-brand',
    aliases: [{ alias: 'Prada' }, { alias: 'Prada S.p.A.', type: 'legal' }, { alias: 'Miu Miu' }],
  },
  {
    slug: 'pandora-jewellery',
    kind: 'company',
    name: 'Pandora',
    legalName: 'Pandora A/S',
    description:
      'Danish affordable-luxury jeweller selling charm bracelets through its own stores worldwide.',
    officialDomain: 'pandoragroup.com',
    ticker: 'PNDORA',
    hq: 'denmark',
    primaryIndustrySlug: 'luxury-goods',
    industrySlugs: ['luxury-goods', 'retail', 'fashion-apparel'],
    businessModelSlug: 'vertical-retail',
    aliases: [
      { alias: 'Pandora A/S', type: 'legal' },
      { alias: 'Pandora Jewelry' },
      { alias: 'Pandora', requiresContext: true },
    ],
  },
  {
    slug: 'reckitt',
    kind: 'company',
    name: 'Reckitt',
    legalName: 'Reckitt Benckiser Group plc',
    description: 'UK hygiene and health group behind Dettol, Finish, Durex and Nurofen.',
    officialDomain: 'reckitt.com',
    ticker: 'RKT',
    hq: 'united-kingdom',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'healthcare'],
    businessModelSlug: 'premium-brand',
    aliases: [
      { alias: 'Reckitt' },
      { alias: 'Reckitt Benckiser', type: 'legal' },
      { alias: 'Dettol' },
      { alias: 'Durex' },
      { alias: 'Finish' },
    ],
  },
  {
    slug: 'beiersdorf',
    kind: 'company',
    name: 'Beiersdorf',
    legalName: 'Beiersdorf Aktiengesellschaft',
    description:
      'German skincare group behind Nivea, Eucerin and La Prairie, plus the tesa adhesives business.',
    officialDomain: 'beiersdorf.com',
    ticker: 'BEI',
    hq: 'germany',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods'],
    businessModelSlug: 'premium-brand',
    aliases: [
      { alias: 'Beiersdorf' },
      { alias: 'Beiersdorf Aktiengesellschaft', type: 'legal' },
      { alias: 'Nivea' },
      { alias: 'Eucerin' },
      { alias: 'La Prairie' },
      { alias: 'tesa' },
    ],
  },
  {
    slug: 'essity',
    kind: 'company',
    name: 'Essity',
    legalName: 'Essity Aktiebolag (publ)',
    description: 'Swedish hygiene and health group behind Tork, Libero, Libresse and TENA.',
    officialDomain: 'essity.com',
    ticker: 'ESSITY-B',
    hq: 'sweden',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'healthcare'],
    businessModelSlug: 'premium-brand',
    aliases: [
      { alias: 'Essity' },
      { alias: 'Essity Aktiebolag', type: 'legal' },
      { alias: 'Tork' },
      { alias: 'TENA' },
      { alias: 'Libresse' },
    ],
  },
  {
    slug: 'ab-inbev',
    kind: 'company',
    name: 'AB InBev',
    legalName: 'Anheuser-Busch InBev SA/NV',
    description:
      'Belgian brewer, the largest in the world, owner of Budweiser, Stella Artois and Corona.',
    officialDomain: 'ab-inbev.com',
    ticker: 'ABI',
    hq: 'belgium',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    businessModelSlug: 'premium-brand',
    aliases: [
      { alias: 'AB InBev' },
      { alias: 'Anheuser-Busch InBev', type: 'legal' },
      { alias: 'Budweiser' },
      { alias: 'Stella Artois' },
    ],
  },
  {
    slug: 'lindt-spruengli',
    kind: 'company',
    name: 'Lindt & Sprüngli',
    legalName: 'Chocoladefabriken Lindt & Sprüngli AG',
    description: 'Swiss premium chocolate maker, owner of Ghirardelli and Russell Stover.',
    officialDomain: 'lindt-spruengli.com',
    ticker: 'LISN',
    hq: 'switzerland',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    businessModelSlug: 'premium-brand',
    aliases: [
      { alias: 'Lindt & Sprüngli' },
      { alias: 'Chocoladefabriken Lindt & Sprüngli', type: 'legal' },
      { alias: 'Lindt' },
      { alias: 'Ghirardelli' },
    ],
  },
  {
    slug: 'arla-foods',
    kind: 'company',
    name: 'Arla Foods',
    legalName: 'Arla Foods amba',
    description:
      'Danish-Swedish dairy co-operative owned by its farmer members, behind Lurpak and Castello.',
    officialDomain: 'arla.com',
    hq: 'denmark',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    businessModelSlug: 'premium-brand',
    aliases: [
      { alias: 'Arla Foods' },
      { alias: 'Arla Foods amba', type: 'legal' },
      { alias: 'Arla' },
      { alias: 'Lurpak' },
    ],
  },
  {
    slug: 'barilla',
    kind: 'company',
    name: 'Barilla',
    legalName: 'Barilla G. e R. Fratelli S.p.A.',
    description: 'Italian family-owned pasta and bakery group, owner of Mulino Bianco and Wasa.',
    officialDomain: 'barillagroup.com',
    hq: 'italy',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    businessModelSlug: 'premium-brand',
    aliases: [
      { alias: 'Barilla' },
      { alias: 'Barilla G. e R. Fratelli', type: 'legal' },
      { alias: 'Mulino Bianco' },
      { alias: 'Wasa' },
    ],
  },
  {
    slug: 'frieslandcampina',
    kind: 'company',
    name: 'FrieslandCampina',
    legalName: 'Koninklijke FrieslandCampina N.V.',
    description:
      'Dutch dairy co-operative owned by member farmers, behind Campina, Optimel and Friso.',
    officialDomain: 'frieslandcampina.com',
    hq: 'netherlands',
    primaryIndustrySlug: 'consumer-goods',
    industrySlugs: ['consumer-goods', 'food-beverage'],
    businessModelSlug: 'premium-brand',
    aliases: [
      { alias: 'FrieslandCampina' },
      { alias: 'Koninklijke FrieslandCampina', type: 'legal' },
      { alias: 'Campina' },
    ],
  },
  {
    slug: 'kingfisher',
    kind: 'company',
    name: 'Kingfisher',
    legalName: 'Kingfisher plc',
    description: 'UK home improvement group behind B&Q, Castorama, Brico Dépôt and Screwfix.',
    officialDomain: 'kingfisher.com',
    ticker: 'KGF',
    hq: 'united-kingdom',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'Kingfisher' },
      { alias: 'Kingfisher plc', type: 'legal' },
      { alias: 'B&Q' },
      { alias: 'Screwfix' },
      { alias: 'Castorama' },
    ],
  },
  {
    slug: 'hornbach',
    kind: 'company',
    name: 'Hornbach',
    legalName: 'HORNBACH Holding AG & Co. KGaA',
    description: 'German DIY and garden centre operator trading across central Europe.',
    officialDomain: 'hornbach-holding.com',
    ticker: 'HBH',
    hq: 'germany',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'Hornbach' },
      { alias: 'HORNBACH Holding', type: 'legal' },
      { alias: 'Hornbach Baumarkt' },
    ],
  },
  {
    slug: 'jysk',
    kind: 'company',
    name: 'JYSK',
    legalName: 'JYSK A/S',
    description:
      'Danish home furnishing chain, privately held and one of the widest store networks in Europe.',
    officialDomain: 'jysk.com',
    hq: 'denmark',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    businessModelSlug: 'vertical-retail',
    aliases: [{ alias: 'JYSK' }, { alias: 'JYSK A/S', type: 'legal' }],
  },
  {
    slug: 'leroy-merlin',
    kind: 'company',
    name: 'Leroy Merlin',
    legalName: 'Adeo SA',
    description:
      'French home improvement retailer, the largest in Europe, held within the Adeo group.',
    officialDomain: 'adeo.com',
    hq: 'france',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [{ alias: 'Leroy Merlin' }, { alias: 'Adeo', type: 'legal' }, { alias: 'Bricoman' }],
  },
  {
    slug: 'fnac-darty',
    kind: 'company',
    name: 'Fnac Darty',
    legalName: 'Fnac Darty SA',
    description: 'French electronics, appliance and cultural goods retailer.',
    officialDomain: 'fnacdarty.com',
    ticker: 'FNAC',
    hq: 'france',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'media-entertainment', 'consumer-goods'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'Fnac Darty' },
      { alias: 'Fnac Darty SA', type: 'legal' },
      { alias: 'Fnac' },
      { alias: 'Darty' },
    ],
  },
  {
    slug: 'currys',
    kind: 'company',
    name: 'Currys',
    legalName: 'Currys plc',
    description:
      'UK and Nordic electricals retailer, trading as Elkjøp and Elgiganten in Scandinavia.',
    officialDomain: 'currysplc.com',
    ticker: 'CURY',
    hq: 'united-kingdom',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'Currys' },
      { alias: 'Currys plc', type: 'legal' },
      { alias: 'Elkjøp' },
      { alias: 'Elgiganten' },
    ],
  },
  {
    slug: 'boots',
    kind: 'company',
    name: 'Boots',
    legalName: 'Boots UK Limited',
    description: 'UK pharmacy-led health and beauty chain, held by Walgreens Boots Alliance.',
    officialDomain: 'boots-uk.com',
    hq: 'united-kingdom',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods', 'healthcare'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'Boots UK', type: 'legal' },
      { alias: 'Walgreens Boots Alliance' },
      { alias: 'Boots', requiresContext: true },
    ],
  },
  {
    slug: 'mueller-drogerie',
    kind: 'company',
    name: 'Müller',
    legalName: 'Müller Holding Ltd. & Co. KG',
    description:
      'German drugstore and general assortment chain, privately held, trading across the Alpine region.',
    officialDomain: 'mueller.de',
    hq: 'germany',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'Müller Holding', type: 'legal' },
      { alias: 'Müller Drogerie' },
      { alias: 'Drogerie Müller' },
    ],
  },
  {
    slug: 'as-watson',
    kind: 'company',
    name: 'A.S. Watson',
    legalName: 'A.S. Watson Group',
    description:
      'Hong Kong health and beauty retailer, owner of Kruidvat, Trekpleister, ICI Paris XL and Superdrug in Europe.',
    officialDomain: 'aswatson.com',
    hq: 'china',
    primaryIndustrySlug: 'retail',
    industrySlugs: ['retail', 'consumer-goods'],
    businessModelSlug: 'multi-brand-retail',
    aliases: [
      { alias: 'A.S. Watson' },
      { alias: 'A.S. Watson Group', type: 'legal' },
      { alias: 'Kruidvat' },
      { alias: 'ICI Paris XL' },
      { alias: 'Superdrug' },
      { alias: 'Trekpleister' },
    ],
  },
];
